Add initial commit for addint support for kubernetes node
cloudify-incubator/kubernetes-node-blueprints pull request #1
Opened 2018-03-27 11:26 UTC by mabuaisha

2018-03-27 12:07 UTC, EarthmanT approved these changes

2018-04-15 17:07 UTC, EarthmanT approved these changes

2018-04-16 08:56 UTC, 0lvin approved these changes

2018-04-30 11:54 UTC, EarthmanT commented on aws.yaml
> +  - imports/cloud-config.yaml
Use 4.3 plugin import syntax, e.g.:
```
  - plugin:cloudify-diamond-plugin
  - plugin:cloudify-fabric-plugin
  - plugin:cloudify-utilities-plugin
  - plugin:cloudify-kubernetes-plugin
  - plugin:cloudify-awssdk-plugin
```

2018-05-02 08:46 UTC, 0lvin requested changes
Remove any binary files, and put to "release attachment to provider."

2018-05-02 08:53 UTC, mabuaisha commented
@0lvin Yeah this should be removed I'm adding this for testing and will remove it once approve everything

2018-05-02 14:45 UTC, 0lvin approved these changes
Looks good. CR done.

2018-05-02 14:47 UTC, merged